# Generated by Django 4.1 on 2022-09-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='watched',
            field=models.CharField(max_length=50),
        ),
    ]
